- name: set up target server 
  hosts: host
  user: '{{ user }}'
  become: true
  become_user: root
  tasks:
  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: make directory
    file:
      path: '/usr/share/nginx/html'
      state: directory
      group: wheel
      owner: '{{ user }}'
      recurse: yes

  - name: git clone
    ansible.builtin.git:
      repo: git@github.com:zawa1120/homepage.git
      dest: /usr/share/nginx/html/homepage
      accept_hostkey: true

  - name: configure the owner and permission in target file
    file:
      path: /usr/share/nginx/html
      group: wheel
      owner: '{{ user }}'
      mode: '775' 
      recurse: yes

  - name: configure the location parts in default.conf
    lineinfile:
      dest: /etc/nginx/conf.d/default.conf
      firstmatch: yes
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - regexp: '^.*root.*/usr/share/nginx/html.*'
        line: '        root   /usr/share/nginx/html/homepage;'
      - regexp: '^.*server_name.*localhost.*'
        line: '    server_name  yuya-hanzawa.com;'

  - name: configure the location parts in https.conf 
    lineinfile:
      dest: /etc/nginx/conf.d/https.conf 
      firstmatch: yes
      regexp: '^.*root.*/usr/share/nginx/html.*'
      line: '        root   /usr/share/nginx/html/homepage;'

  - name: delete lines in nginx.conf
    lineinfile:
      dest: /etc/nginx/nginx.conf
      state: absent
      regexp: "{{ item }}"
    with_items:
      - '^.*remote_addr.*'
      - '^.*status.*'
      - '^.*http_user_agent.*'

  - name: modify log format in nginx.conf 
    blockinfile:
      dest: /etc/nginx/nginx.conf
      insertafter: '.*application/octet-stream;'
      block: |2
            log_format json escape=json '{"time": "$time_iso8601",'
                                         '"remote_host": "$remote_addr",'
                                         '"host": "$host",'
                                         '"user": "$remote_user",'
                                         '"status": "$status",'
                                         '"protocol": "$server_protocol",'
                                         '"method": "$request_method",'
                                         '"path": "$request_uri",'
                                         '"req": "$request",'
                                         '"size": "$body_bytes_sent",'
                                         '"request_time": "$request_time",'
                                         '"upstream_time": "$upstream_response_time",'
                                         '"user_agent": "$http_user_agent",'
                                         '"forwardedfor": "$http_x_forwarded_for",'
                                         '"forwardedproto": "$http_x_forwarded_proto",'
                                         '"referrer": "$http_referer"}';

  - name: modify log format in nginx.conf
    lineinfile:
      dest: /etc/nginx/nginx.conf
      regexp: '.*/var/log/nginx/access.log.*'
      line: '    access_log /var/log/nginx/access.log json;'

  - name: modify logrotate.d/nginx
    lineinfile:
      dest: /etc/logrotate.d/nginx
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - regexp: '.*create.*'
        line: '        create 775 {{ user }} wheel'
      - regexp: '.*rotate.*'
        line: '        rotate 7'

  - name: modify logrotate.d/nginx
    lineinfile:
      dest: /etc/logrotate.d/nginx
      state: absent
      regexp: '.*compress.*'

  - name: restart logrotate
    command:
      cmd: 'logrotate -f /etc/logrotate.conf'

  - name: modify sshd_config
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '{{ item.regexp }}'
      line: '{{ item.line }}'
    with_items:
      - regexp: '^#Port.*'
        line: 'Port {{ port }}'
      - regexp: '^#PermitRootLogin.*'
        line: 'PermitRootLogin no'
      - regexp: '^#PermitEmptyPasswords.*'
        line: 'PermitEmptyPasswords no'

  - name: restart sshd
    service:
      name: sshd
      state: restarted

  - name: started firewall
    systemd:
      name: firewalld
      state: started
      enabled: yes

  - name: firewalld enable ssh port
    firewalld:
      port: '{{ port }}/tcp'
      permanent: yes
      state: enabled
      immediate: true

  - name: firewalld disabled ssh
    firewalld:
      service: ssh
      permanent: yes
      state: disabled
      immediate: true
  
  - name: firewalld enable http, https
    firewalld:
      service: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: true
    with_items:
      - http
      - https

  - name: restart nginx
    service:
      name: nginx
      state: restarted
